### ISSUE TITLE
Grid size & obstacle probability 

### ISSUE THREAD

**Issue by kidist-123** [vss2sn/path_planning#4]
Hey, this is kidist ,
I want to run the algorithms on the large grid size and the obstacle probability is 1/n .So, does it mean the number of obstacles will decrease as we increase the grid size n ?
Thank you !

**Comment by vss2sn** [comment]
No, as the number of points on the grid scales by n*n. 
The grid might look sparser as the ratio of the number of obstacles to points on the grid will decrease with an increasing n.
