### ISSUE TITLE
Grid type 

### ISSUE THREAD

**Issue by Didi-1221** [vss2sn/path_planning#5]
Hey, I saw your code it is an excellent implementation. I have a question on what kind of graph/grid you applied. is it visibility graph,Sukharev grid? 
Thank you

**Comment by vss2sn** [comment]
Thank you!  
In terms if visibility a point on the grid is known to be an obstacle only when it is expanded in the algorithm.
The grid here is a simple 2D grid; thinking of it in terms of a Sukharev grid might make following the algorithms more complex than necessary. The only place it might be useful is when considering the obstacle detection for RRT and RRT*, to check whether the start and end point have a direct line of sight, and even here it is better understood intuitively, i.e. if the line connecting the two points, passes near a point which is an obstacle, the corresponding motion is invalid.
